apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cs-frontend-cert
  namespace: ns-cs
spec:
  secretName: cs-frontend-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - web-cs.software
