version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: fatec
      MYSQL_DATABASE: CadastroSocial
      MYSQL_USER: dev
      MYSQL_PASSWORD: fatec
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: