import { PrismaClient } from "@prisma/client";

enum SituacaoAssistidoEnum {
  RUA = "Na rua",
  RECUPERACAO = "Em recuperação",
  RECUPERADO = "Recuperado",
}

const prisma = new PrismaClient();

async function main() {
  // Inserindo usuários
  await prisma.usuario.createMany({
    data: [
      {
        nome: "João Silva",
        telefone: "11999999999",
        email: "joao.silva@example.com",
        senha: "senha123",
        ativo: true,
      },
      {
        nome: "Maria Oliveira",
        telefone: "21988888888",
        email: "maria.oliveira@example.com",
        senha: "senha456",
        ativo: true,
      },
      {
        nome: "Carlos Pereira",
        telefone: "31977777777",
        email: "carlos.pereira@example.com",
        senha: "senha789",
        ativo: false,
      },
    ],
  });

  // Inserindo quadros de aviso
  await prisma.quadroAviso.createMany({
    data: [{ id: 1 }, { id: 2 }],
  });

  // Inserindo avisos
  await prisma.aviso.createMany({
    data: [
      {
        titulo: "Precisa de novos sapatos",
        descricao: "Precisamos de novos sapatos para os moradores tamanho 41.",
        quadroAvisoId: 1,
      },
      {
        titulo: "Novo procedimento",
        descricao: "Atualização dos procedimentos internos.",
        quadroAvisoId: 2,
      },
    ],
  });

  // Criando 20 assistidos com campos adicionais
  const assistidos = [
    {
      nome: "Carlos",
      data_nascimento: new Date(1985, 3, 15),
      situacao: SituacaoAssistidoEnum.RUA,
      sexo: "Masculino",
      familiar_proximo: true,
      estado_civil: "Solteiro",
      motivo_saiu: "Problemas familiares",
      filhos: true,
      existe_contato: true,
      descricao: "Morador de rua há 5 anos",
      ativo: true,
    },
    {
      nome: "Ana",
      data_nascimento: new Date(1990, 6, 21),
      situacao: SituacaoAssistidoEnum.RECUPERACAO,
      sexo: "Feminino",
      familiar_proximo: false,
      estado_civil: "Casada",
      motivo_saiu: "Problemas de saúde",
      filhos: false,
      existe_contato: true,
      descricao: "Em recuperação após uso de substâncias",
      ativo: true,
    },
    {
      nome: "João",
      data_nascimento: new Date(1975, 11, 10),
      situacao: SituacaoAssistidoEnum.RECUPERADO,
      sexo: "Masculino",
      familiar_proximo: true,
      estado_civil: "Divorciado",
      motivo_saiu: "Abandono de lar",
      filhos: true,
      existe_contato: false,
      descricao: "Recuperado de problemas com álcool",
      ativo: true,
    },
    {
      nome: "Maria",
      data_nascimento: new Date(1980, 2, 5),
      situacao: SituacaoAssistidoEnum.RUA,
      sexo: "Feminino",
      familiar_proximo: false,
      estado_civil: "Solteira",
      motivo_saiu: "Perda de emprego",
      filhos: false,
      existe_contato: true,
      descricao: "Vive nas ruas após dificuldades financeiras",
      ativo: true,
    },
    {
      nome: "Pedro",
      data_nascimento: new Date(2000, 8, 30),
      situacao: SituacaoAssistidoEnum.RECUPERACAO,
      sexo: "Masculino",
      familiar_proximo: true,
      estado_civil: "Solteiro",
      motivo_saiu: "Desentendimentos familiares",
      filhos: false,
      existe_contato: true,
      descricao: "Em processo de reabilitação",
      ativo: true,
    },
    {
      nome: "Julia",
      data_nascimento: new Date(1995, 0, 13),
      situacao: SituacaoAssistidoEnum.RECUPERADO,
      sexo: "Feminino",
      familiar_proximo: true,
      estado_civil: "Casada",
      motivo_saiu: "Divórcio",
      filhos: false,
      existe_contato: true,
      descricao: "Recuperada de problemas de dependência",
      ativo: true,
    },
    {
      nome: "Roberto",
      data_nascimento: new Date(1988, 9, 17),
      situacao: SituacaoAssistidoEnum.RUA,
      sexo: "Masculino",
      familiar_proximo: false,
      estado_civil: "Solteiro",
      motivo_saiu: "Desemprego",
      filhos: false,
      existe_contato: false,
      descricao: "Vive nas ruas após perder emprego",
      ativo: true,
    },
    {
      nome: "Claudia",
      data_nascimento: new Date(1983, 4, 9),
      situacao: SituacaoAssistidoEnum.RECUPERACAO,
      sexo: "Feminino",
      familiar_proximo: true,
      estado_civil: "Viúva",
      motivo_saiu: "Problemas de saúde",
      filhos: true,
      existe_contato: true,
      descricao: "Em tratamento psiquiátrico",
      ativo: true,
    },
    {
      nome: "Fernando",
      data_nascimento: new Date(1970, 7, 25),
      situacao: SituacaoAssistidoEnum.RECUPERADO,
      sexo: "Masculino",
      familiar_proximo: true,
      estado_civil: "Casado",
      motivo_saiu: "Problemas financeiros",
      filhos: true,
      existe_contato: true,
      descricao: "Recuperado de dependência química",
      ativo: true,
    },
    {
      nome: "Laura",
      data_nascimento: new Date(1992, 11, 2),
      situacao: SituacaoAssistidoEnum.RUA,
      sexo: "Feminino",
      familiar_proximo: false,
      estado_civil: "Solteira",
      motivo_saiu: "Abuso doméstico",
      filhos: false,
      existe_contato: false,
      descricao: "Moradora de rua após abusos sofridos",
      ativo: true,
    },
    {
      nome: "Gabriel",
      data_nascimento: new Date(1987, 3, 19),
      situacao: SituacaoAssistidoEnum.RECUPERACAO,
      sexo: "Masculino",
      familiar_proximo: true,
      estado_civil: "Solteiro",
      motivo_saiu: "Desentendimento familiar",
      filhos: false,
      existe_contato: true,
      descricao: "Em recuperação após uso de drogas",
      ativo: true,
    },
    {
      nome: "Patricia",
      data_nascimento: new Date(1981, 5, 22),
      situacao: SituacaoAssistidoEnum.RECUPERADO,
      sexo: "Feminino",
      familiar_proximo: true,
      estado_civil: "Casada",
      motivo_saiu: "Problemas de relacionamento",
      filhos: false,
      existe_contato: true,
      descricao: "Recuperada de problemas financeiros",
      ativo: true,
    },
    {
      nome: "Carlos Eduardo",
      data_nascimento: new Date(1978, 10, 3),
      situacao: SituacaoAssistidoEnum.RUA,
      sexo: "Masculino",
      familiar_proximo: false,
      estado_civil: "Divorciado",
      motivo_saiu: "Perda de emprego",
      filhos: true,
      existe_contato: false,
      descricao: "Vive nas ruas após desemprego",
      ativo: true,
    },
    {
      nome: "Sofia",
      data_nascimento: new Date(2005, 2, 15),
      situacao: SituacaoAssistidoEnum.RECUPERACAO,
      sexo: "Feminino",
      familiar_proximo: true,
      estado_civil: "Solteira",
      motivo_saiu: "Abuso psicológico",
      filhos: false,
      existe_contato: true,
      descricao: "Recuperação após abuso familiar",
      ativo: true,
    },
    {
      nome: "Felipe",
      data_nascimento: new Date(1998, 6, 27),
      situacao: SituacaoAssistidoEnum.RECUPERADO,
      sexo: "Masculino",
      familiar_proximo: true,
      estado_civil: "Solteiro",
      motivo_saiu: "Problemas de saúde",
      filhos: false,
      existe_contato: true,
      descricao: "Recuperado de depressão",
      ativo: true,
    },
    {
      nome: "Isabela",
      data_nascimento: new Date(1994, 1, 18),
      situacao: SituacaoAssistidoEnum.RUA,
      sexo: "Feminino",
      familiar_proximo: true,
      estado_civil: "Solteira",
      motivo_saiu: "Problemas de saúde mental",
      filhos: false,
      existe_contato: true,
      descricao: "Vive nas ruas após crise emocional",
      ativo: true,
    },
    {
      nome: "Ricardo",
      data_nascimento: new Date(1984, 8, 14),
      situacao: SituacaoAssistidoEnum.RECUPERACAO,
      sexo: "Masculino",
      familiar_proximo: true,
      estado_civil: "Casado",
      motivo_saiu: "Problemas com vícios",
      filhos: true,
      existe_contato: false,
      descricao: "Em recuperação após dependência química",
      ativo: true,
    },
    {
      nome: "Fernanda",
      data_nascimento: new Date(1991, 11, 20),
      situacao: SituacaoAssistidoEnum.RECUPERADO,
      sexo: "Feminino",
      familiar_proximo: true,
      estado_civil: "Casada",
      motivo_saiu: "Problemas financeiros",
      filhos: false,
      existe_contato: true,
      descricao: "Recuperada de problemas psicológicos",
      ativo: true,
    },
    {
      nome: "Alexandre",
      data_nascimento: new Date(1993, 4, 9),
      situacao: SituacaoAssistidoEnum.RUA,
      sexo: "Masculino",
      familiar_proximo: false,
      estado_civil: "Solteiro",
      motivo_saiu: "Problemas familiares",
      filhos: false,
      existe_contato: false,
      descricao: "Morador de rua devido a dificuldades familiares",
      ativo: true,
    },
    {
      nome: "Tatiane",
      data_nascimento: new Date(1972, 9, 25),
      situacao: SituacaoAssistidoEnum.RECUPERACAO,
      sexo: "Feminino",
      familiar_proximo: true,
      estado_civil: "Divorciada",
      motivo_saiu: "Problemas psicológicos",
      filhos: true,
      existe_contato: true,
      descricao: "Em recuperação após trauma psicológico",
      ativo: true,
    },
  ];
  // Inserindo assistidos no banco
  for (let assistido of assistidos) {
    await prisma.assistido.create({
      data: assistido,
    });
  }

  console.log("Assistidos criados com sucesso!");
}

main()
  .catch((e) => {
    console.error(e);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
